apiVersion: v1
kind: Pod
metadata:       
  name: nginx   #name of pod
  labels:
     env: testing    #what label should attach to that pod 
     env1: dev
spec:               #pod contains what? at least contain a container
  containers:
  - name: nginx         #name of container
    image: nginx:1.14.2      #container imamge
    ports:
    - containerPort: 80
