-kubectl create ns test    .....{create a namespace of name test}
-create a pod 
-kubectl apply -f abc.yml --namespace test  ...{a pod is created in test namespace}
-if you run $ kubectl get pod command you would not get your pod as your pod is running on test namespace but
,default namespace of kubenetes id default . 

-kubectl get pod -n test  ...{to get your pod}

-kubectl get pod --all-namespaces ...{to check all pods running on which namespaces}
-kubectl delete pod pod2 -n test  ...{to delete pod running on test ns} 

-----------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: test   ........{provide ns in yml file}
  labels:
     env: testing
     type: app
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
-----------------------------------------------------------------------------------------------------------------------
kubectl get ns
    NAME              STATUS   AGE
    default           Active   3h36m
    kube-node-lease   Active   3h36m
    kube-public       Active   3h36m
    kube-system       Active   3h36m
    test              Active   115m
-----------------------------------------------------------------------------------------------------------------------   
kubectl get pod -n kube-system ...{all these pods will ensure management system of master node}
    NAME                               READY   STATUS    RESTARTS        AGE
    coredns-674b8bbfcf-ljdc7           1/1     Running   0               3h36m
    etcd-minikube                      1/1     Running   0               3h36m  ...{database manage}
    kube-apiserver-minikube            1/1     Running   0               3h36m
    kube-controller-manager-minikube   1/1     Running   0               3h36m
    kube-proxy-q2825                   1/1     Running   0               3h36m  ...{networking manage}
    kube-scheduler-minikube            1/1     Running   0               3h36m  ...{scheduling of pod}
    storage-provisioner                1/1     Running   1 (3h35m ago)   3h36m
-----------------------------------------------------------------------------------------------------------------------
kubectl config set-context --current --namespace=test ....{to make test namespace as default namespace}    
