apiVersion: v1
kind: ReplicationController
metadata:
  name: firstreplica
spec:
  replicas: 3
  template:
    metadata:
      name: firstpod1
      labels:
        type : app
    spec:
      containers:
      - name: nginx
        image: nginx
#kubectl delete rc --cascade=false <rc_name>  ...{it just delete the rc but pod remains in running condition}
        
        

